# Generated by Django 3.2.5 on 2022-11-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BgRemover', '0002_alter_image_rmbg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='BgRemover'),
        ),
    ]
